{% set name = "django-removals" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django_removals-{{ version }}.tar.gz
  sha256: e838b23a82a5e82fd27935f18db21c7da1eb75ef7e00fce1903996c35bbc137f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.4
    - pip
  run:
    - python >={{ python_min }}
    - django >=4.2

test:
  imports:
    - django_removals
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ambient-innovation/django-removals/
  summary: Tool for finding removed features in your Django project
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - thewchan
